### ISSUE TITLE
Excessive "Message previously routed" Errors

### ISSUE THREAD

**Issue by yuilleb** [kadtools/kad-quasar#11]
When looking at @1credit's connections he noted that he currently had over 800 tcp connections established with another peer. We did a packet capture on that peer's IP address and found that amazingly almost all the traffic was failing with either "Message has expired" (should be fixed now with #10) or "Message previously routed".

Would this be considered normal proper traffic? If so, can we think of a smarter way to handle these errors?

It seems to me the peer is already receiving these PUBLISH messages from some other node that is clearly a faster source than @1credit. So in such a case could we simply stop relaying to this peer until he signals his neighbors have changed?

I haven't thought much about the details here yet, but I want to get a discussion going about is there a smarter way to perhaps prevent duplicate PUBLISH messages from spamming nodes on the network.

Redundancy in a pub/sub network is good, but is it really necessary to receive the redundant data at the same time? I'm wondering if perhaps it might be best to simply subscribe to one of your neighbors for relayed messages and then upon detecting problems with that neighbor you fail over to another neighbor for subscribing to relayed messages.

Does the algorithm only work if you relay PUBLISH messages to all of your nearest neighbors? In the case of @1credit, his peer was clearly receiving duplicate PUBLISH messages from the same part of the network as @1credit. Is there anyway to isolate this so that @1credit can filter which messages his peer is likely to have already received from that same area of the network?

**Comment by littleskunk** [comment]
It looks like the bridge itself is sending different uuids. All nodes will relay PUBLISH messages 3 times. The "Message previously routed" is correct and expected: https://github.com/Storj/core/issues/486

**Comment by littleskunk** [comment]
skunk in reply to your post just now on github: the only way a node can reply with "Message previously routed" is if it's seen the same uuid. so I don't beleive sending out 3 pub messages with the same content yet different uuid's makes a difference, there would simply be 3 times less "Message previously routed" errors in that capture file.

skunk [08:38]  
correct
You are looking for a way to tell Alice she is always to slow and should stop it?

bwy [08:39]  
not really sure
I guess I'm wondering if there's a way to stop sending redundant pub messages to a node
... until that node signals it needs them

skunk [08:40]  
Alice I would like to unsubscribe your newsletter :smile:

bwy [08:41]  
cassey should never have 800+ connections to a node that are all failing with "Message has expired" or "Message previously routed" that's just a complete waste. if perhaps 2 of each pub message were duplicates from your issue, then that's still a lot of wasteful messages (something like 250 connections)
exactly, that would be nice to have an unsubscribe :slightly_smiling_face: (edited)
