### ISSUE TITLE
_relayToRandomNeighbor exception callback is not a function 

### ISSUE THREAD

**Issue by littleskunk** [kadtools/kad-quasar#28]
Farmer started and receiving PUBLISH message very early. My farmer has to random Relay these mssages because the bloom lifter will be merged later.

I see this error on the GUI developer console.
```
Uncaught TypeError: callback is not a function
Quasar._sendPublish @ C:\Program Files\Storj Share\resources\app\node_modules\kad-quasar\lib\quasar.js:179
_relayToRandomNeighbor @ C:\Program Files\Storj Share\resources\app\node_modules\kad-quasar\lib\quasar.js:284
...
```

https://github.com/kadtools/kad-quasar/blob/master/lib/quasar.js#L284

**Comment by bookchin** [comment]
Fixed in 1.2.3
