### ISSUE TITLE
TypeError: Cannot read property 'bitfield' of undefined

### ISSUE THREAD

**Issue by 1credit** [kadtools/kad-quasar#8]
`/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad-quasar/lib/bloomfilter.js:47
    bf.filters[i].bitfield.buffer = new Buffer(filters[i], 'hex');
                 ^

TypeError: Cannot read property 'bitfield' of undefined
    at Function.BloomFilter.deserialize (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad-quasar/lib/bloomfilter.js:47:18)
    at Object.callback (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad-quasar/lib/quasar.js:362:32)
    at Transport.RPC._execPendingCallback (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/rpc.js:331:17)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/rpc.js:235:12
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/rpc.js:305:5
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:251:17
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:154:25
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:248:21
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:612:34
    at Transport.protocol (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/lib/hooks/protocol.js:21:14)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:607:21
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:246:17
    at iterate (/usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:146:13)
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:157:25
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:248:21
    at /usr/lib64/node_modules/storjshare-cli/node_modules/storj-lib/node_modules/kad/node_modules/async/lib/async.js:612:34
`

**Comment by arichnad** [comment]
I'm also seeing this bug.  Same callstack ( bloomfilter.js:47 ).

**Comment by bookchin** [comment]
Looks like this happens when a neighbor sends back more bloom filters in the response than they are supposed to and we aren't safely checking. This would only happen if the remote host is running with modified constants. Fix incoming.

**Comment by bookchin** [comment]
Closed by https://github.com/kadtools/kad-quasar/releases/tag/v0.2.1

**Comment by deadgray** [comment]
I have it too. What worked was to just wait some time and run -cli, but few restarts before didn't work.

**Comment by 1credit** [comment]
What do we need to do to incorporate this into our run environments?  Just uninstall/install storjshare-cli???

**Comment by bookchin** [comment]
Yeah just reinstall @next
